name = "jl_cockpit"
uuid = "44272be6-8374-4492-a716-50d0e891cc14"
authors = ["Niklas Schlüter niklas.schlueter@tu-berlin.de"]
version = "1.0.0-DEV"

[deps]
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
FluxTraining = "0.3"
Makie = "0.22"
julia = "1.11"
